#pragma once
// auto generated by IncludeBuilder

#include <Native/Windows/stdafx.h>
#include <Native/Windows/API/Audio/XAudio/XAudioAPI.h>
#include <Native/Windows/API/Audio/XAudio/XAudioSound.h>
#include <Native/Windows/API/Graphics/DX9/DX9Constants.h>
#include <Native/Windows/API/Graphics/DX9/DX9GraphicsAPI.h>
#include <Native/Windows/API/Graphics/DX9/DX9IndexBuffer.h>
#include <Native/Windows/API/Graphics/DX9/DX9Shader.h>
#include <Native/Windows/API/Graphics/DX9/DX9VertexBuffer.h>
#include <Native/Windows/API/Graphics/DX9/imgui/imgui_impl_dx9.h>
#include <Native/Windows/API/Graphics/WindowsGraphicsAPI.h>
#include <Native/Windows/API/Input/DirectInput/DirectInputAPI.h>
#include <Native/Windows/API/Input/DirectInput/DirectInputDevice.h>
#include <Native/Windows/API/Input/DirectInput/DirectInputDeviceManager.h>
#include <Native/Windows/API/Input/DirectInput/DirectInputDevice_Keyboard.h>
#include <Native/Windows/API/Input/DirectInput/DirectInputDevice_Mouse.h>
#include <Native/Windows/API/Input/DirectInput/DirectInputDevice_XInput.h>
#include <Native/Windows/API/Input/DirectInput/DirectInputImplements.h>
#include <Native/Windows/DX9EntryPoint.h>
#include <Native/Windows/PlatformSetting_DX11.h>
#include <Native/Windows/WindowsActivity.h>

