#pragma once

#if GG_GRAPHICS_API_DX11

#include <d3d11.h>

namespace DX11
{

static DXGI_FORMAT INDEX_FORMATS[static_cast<T_UINT32>(Vertex::IndexFormat::INDEX_FMT_DATANUM)] =
{
  DXGI_FORMAT_R16_UINT,
  DXGI_FORMAT_R32_UINT,
};

static const D3D_PRIMITIVE_TOPOLOGY PRIMITIVE_TYPES[static_cast<T_UINT32>(Vertex::PrimitiveType::DATANUM)] =
{
  D3D11_PRIMITIVE_TOPOLOGY_POINTLIST,
  D3D11_PRIMITIVE_TOPOLOGY_LINELIST,
  D3D11_PRIMITIVE_TOPOLOGY_LINESTRIP,
  D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST,
  D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP,
  D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP,
};


}

#endif
