#pragma once

#if GG_GRAPHICS_API_DX11

#include <d3d11.h>

namespace DX11
{

static DXGI_FORMAT INDEX_FORMATS[static_cast<T_UINT32>(Vertex::IndexFormat::INDEX_FMT_DATANUM)] =
{
  DXGI_FORMAT_R16_UINT,
  DXGI_FORMAT_R32_UINT,
};

static const D3D_PRIMITIVE_TOPOLOGY PRIMITIVE_TYPES[static_cast<T_UINT32>(Vertex::PrimitiveType::DATANUM)] =
{
  D3D11_PRIMITIVE_TOPOLOGY_POINTLIST,
  D3D11_PRIMITIVE_TOPOLOGY_LINELIST,
  D3D11_PRIMITIVE_TOPOLOGY_LINESTRIP,
  D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST,
  D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP,
  D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP,
};

static const D3D11_CULL_MODE CULL_MODES[static_cast<T_UINT8>(Shader::CullMode::DATANUM)] =
{
  D3D11_CULL_BACK,
  D3D11_CULL_FRONT,
  D3D11_CULL_NONE,
};

static const D3D11_DEPTH_WRITE_MASK Z_WRITES[static_cast<T_UINT8>(Shader::ZWrite::DATANUM)] =
{
  D3D11_DEPTH_WRITE_MASK_ALL,
  D3D11_DEPTH_WRITE_MASK_ZERO,
};

static const D3D11_COMPARISON_FUNC COMPARASION_FUNCS[static_cast<T_UINT8>(Shader::ComparasionFunc::DATANUM)] =
{
  D3D11_COMPARISON_LESS,
  D3D11_COMPARISON_GREATER,
  D3D11_COMPARISON_LESS_EQUAL,
  D3D11_COMPARISON_GREATER_EQUAL,
  D3D11_COMPARISON_EQUAL,
  D3D11_COMPARISON_NOT_EQUAL,
  D3D11_COMPARISON_ALWAYS,
};

static const D3D11_BLEND BLEND_FACTORS[static_cast<T_UINT8>(Shader::BlendFactor::DATANUM)] =
{
  D3D11_BLEND_ONE,
  D3D11_BLEND_ZERO,
  D3D11_BLEND_SRC_COLOR,
  D3D11_BLEND_SRC_ALPHA,
  D3D11_BLEND_DEST_COLOR,
  D3D11_BLEND_DEST_ALPHA,
  D3D11_BLEND_INV_SRC_COLOR,
  D3D11_BLEND_INV_SRC_ALPHA,
  D3D11_BLEND_INV_DEST_COLOR,
  D3D11_BLEND_INV_DEST_ALPHA
};

static const D3D11_BLEND_OP BLEND_OPERATIONS[static_cast<T_UINT8>(Shader::BlendOp::DATANUM)] =
{
  D3D11_BLEND_OP_ADD,
  D3D11_BLEND_OP_SUBTRACT,
  D3D11_BLEND_OP_REV_SUBTRACT,
  D3D11_BLEND_OP_MIN,
  D3D11_BLEND_OP_MAX,
};

static const D3D11_STENCIL_OP STENCIL_OPERATIONS[static_cast<T_UINT8>(Shader::StencilOperation::DATANUM)] =
{
  D3D11_STENCIL_OP_KEEP,
  D3D11_STENCIL_OP_ZERO,
  D3D11_STENCIL_OP_REPLACE,
  D3D11_STENCIL_OP_INCR_SAT,
  D3D11_STENCIL_OP_DECR_SAT,
  D3D11_STENCIL_OP_INVERT,
  D3D11_STENCIL_OP_INCR,
  D3D11_STENCIL_OP_DECR,
};

}

#endif
