#pragma once
// auto generated by IncludeBuilder

#include <Core/stdafx.h>
#include <Core/Allocator/PoolAllocator.h>
#include <Core/Constants/DirectoryUtils.h>
#include <Core/Constants/GraphicsUtils.h>
#include <Core/Constants/VertexUtils.h>
#include <Core/Logger/Logger.h>
#include <Core/Macro/AssertMacro.h>
#include <Core/Macro/ObjectMacro.h>
#include <Core/Macro/ProgramMacro.h>
#include <Core/Math/Bounds.h>
#include <Core/Math/Color.h>
#include <Core/Math/Mathf.h>
#include <Core/Math/Matrix4x4.h>
#include <Core/Math/Quaternion.h>
#include <Core/Math/ScalingMatrix.h>
#include <Core/Math/TranslationMatrix.h>
#include <Core/Math/Vector2.h>
#include <Core/Math/Vector3.h>
#include <Core/Math/Vector4.h>
#include <Core/Native/NativeProcess.h>
#include <Core/Object/Object.h>
#include <Core/Object/ObjectManager.h>
#include <Core/Object/Ref.h>
#include <Core/Object/SharedRef.h>
#include <Core/Object/UniqueRef.h>
#include <Core/Resource/IndexBuffer.h>
#include <Core/Resource/RenderBuffer.h>
#include <Core/Resource/VertexBuffer.h>
#include <Core/Types.h>
#include <Core/_Private/CerealIO.h>

