#pragma once
// auto generated by IncludeBuilder

#include <Core/Common/Allocator/PoolAllocator.h>
#include <Core/Common/Logger.h>
#include <Core/Common/Math/Bounds.h>
#include <Core/Common/Math/Color.h>
#include <Core/Common/Math/Mathf.h>
#include <Core/Common/Math/Matrix4x4.h>
#include <Core/Common/Math/Quaternion.h>
#include <Core/Common/Math/ScalingMatrix.h>
#include <Core/Common/Math/TranslationMatrix.h>
#include <Core/Common/Math/Vector2.h>
#include <Core/Common/Math/Vector3.h>
#include <Core/Common/Math/Vector4.h>
#include <Core/Common/Types.h>
#include <Core/Constants/BlendFunction.h>
#include <Core/Constants/Directory.h>
#include <Core/Constants/GraphicsConstants.h>
#include <Core/Macro/AssertMacro.h>
#include <Core/Macro/ObjectMacro.h>
#include <Core/Macro/ProgramMacro.h>
#include <Core/Native/NativeProcess.h>
#include <Core/Object/Object.h>
#include <Core/Object/ObjectManager.h>
#include <Core/Object/Ref.h>
#include <Core/Object/SharedRef.h>
#include <Core/Object/UniqueRef.h>
#include <Core/Resource/IndexBuffer.h>
#include <Core/Resource/RenderBuffer.h>
#include <Core/Resource/VertexBuffer.h>
#include <Core/Resource/VertexHelper.h>
#include <Core/_Private/CerealIO.h>

