#pragma once

#include <d3d9.h>
#include "INativeProcess_Graphics.h"


namespace NativeConstants
{

static const DWORD FVF_TYPES[Vertex::VERTEX_TYPE_DATANUM] =
{
  D3DFVF_XYZW | D3DFVF_DIFFUSE,
  D3DFVF_XYZW | D3DFVF_DIFFUSE | D3DFVF_TEX1,
  D3DFVF_XYZW | D3DFVF_DIFFUSE | D3DFVF_TEX1 | D3DFVF_NORMAL,
};

static const D3DPRIMITIVETYPE PRIMITIVE_TYPES[INativeProcess_Graphics::PRIMITIVE_DATANUM] =
{
  D3DPT_POINTLIST,
  D3DPT_LINELIST,
  D3DPT_LINESTRIP,
  D3DPT_TRIANGLELIST,
  D3DPT_TRIANGLESTRIP,
  D3DPT_TRIANGLEFAN,
};

}